### ISSUE TITLE
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that don't all match.

### ISSUE THREAD

**Issue by RobertWang2** [searchlink/competition#1]
x1_in = keras.layers.Input(shape=(None,)) # 待识别句子输入
x2_in = keras.layers.Input(shape=(None,)) # 待识别句子输入
bert_output = bert_model([x1_in, x2_in])
lstm = keras.layers.Bidirectional(keras.layers.LSTM(units=128, return_sequences=True))(bert_output)
drop = keras.layers.Dropout(0.25)(lstm)
dense = keras.layers.TimeDistributed(keras.layers.Dense(128, activation="relu"))(drop)
crf = CRF(n_tags)
# print(type(dense))
out = crf(dense)
model = keras.models.Model(inputs=[x1_in, x2_in], outputs=out)
model.compile(loss=crf.loss_function, optimizer='adam', metrics=[crf.accuracy])
# model.compile(loss=keras.losses.crf_loss, optimizer='adam', metrics=[keras.metrics.crf_accuracy])
model.summary()

out = crf(dense)这行报错了，说是bool float32不匹配

**Comment by Wilson-ZHANG** [comment]
附议一下，同样的报错，keras的version可以share一下吗？或者给个requirements.txt～

Thx.





Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 455, in _apply_op_helper
    as_ref=input_arg.is_ref)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1240, in internal_convert_n_to_tensor
    ctx=ctx))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 977, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype bool for Tensor with dtype float32: 'Tensor("crf_1/zeros_like_4:0", shape=(?, ?), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "import.py", line 236, in <module>
    out = crf(dense)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/keras/engine/base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/keras_contrib/layers/crf.py", line 292, in call
    test_output = self.viterbi_decoding(X, mask)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/keras_contrib/layers/crf.py", line 564, in viterbi_decoding
    argmin_tables = self.recursion(input_energy, mask, return_logZ=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/keras_contrib/layers/crf.py", line 516, in recursion
    mask2 = K.cast(K.concatenate([mask, K.zeros_like(mask[:, :1])], axis=1),
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2176, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1256, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1149, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 483, in _apply_op_helper
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, float32] that don't all match.

**Comment by searchlink** [comment]
hi, keras的版本问题，keras==2.2.4 , 预祝取得好成绩！
